[tool.black]
line-length = 79
target-version = ["py310"]

[tool.isort]
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Third-Party"
import_heading_firstparty = "First-Party"
import_heading_localfolder = "Local Folder"
profile = "black"
